# -*- coding: utf-8 -*-
"""Spleeter Project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j2x2kUoaKiODeX4GfxyrqQ86RzusPkuv
"""

!apt install ffmpeg #for converting and processing audio/video formats
!pip install librosa #for analysis of music/audio
!pip install youtube-dl #for downloading video/audio from youtube

pip install spleeter #for separating audio/song into parts (vocals, drums, bass, piano, other)

import librosa
import youtube_dl

from IPython.display import Audio, display
from IPython.display import HTML

! pip3 install pydub

from google.colab import files
import IPython.display as ipd
import sys

url = "tk0DpND0vgA" #@param {type:"string"}
embed_url = "https://www.youtube.com/watch?v=tk0DpND0vgA".format(url)
HTML('<iframe width="560" height="315" src="https://www.youtube.com/embed/tk0DpND0vgA" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>')

ydl_args = {
    'format': 'bestaudio/best',
    'outtmpl': 'nograss.mp3'
}

with youtube_dl.YoutubeDL(ydl_args) as ydl:
    _ = ydl.download([url])

audio, rate = librosa.load('nograss.mp3', sr=44100, mono=False)

display(Audio(audio[:, 0*rate:40*rate], rate=rate))

!spleeter separate -p spleeter:4stems -o output/ nograss.mp3

!spleeter separate -p spleeter:5stems -o output/ nograss.mp3

!ls output/ nograss.mp3

from pydub import AudioSegment
sound = AudioSegment.from_wav("output/nograss/vocals.wav")
sound.export("output/nograss/vocals.mp3", format="mp3")
sound = AudioSegment.from_wav("output/nograss/drums.wav")
sound.export("output/nograss/drums.mp3", format="mp3")
sound = AudioSegment.from_wav("output/nograss/bass.wav")
sound.export("output/nograss/bass.mp3", format="mp3")
sound = AudioSegment.from_wav("output/nograss/other.wav")
sound.export("output/nograss/other.mp3", format="mp3")
sound = AudioSegment.from_wav("output/nograss/piano.wav")
sound.export("output/nograss/piano.mp3", format="mp3")

ipd.Audio('output/nograss/vocals.mp3')

ipd.Audio('output/nograss/drums.mp3')

ipd.Audio('output/nograss/bass.mp3')

ipd.Audio('output/nograss/other.mp3')

ipd.Audio('output/nograss/piano.mp3')