# -*- coding: utf-8 -*-
"""Spleeter Project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j2x2kUoaKiODeX4GfxyrqQ86RzusPkuv
"""

!pip install youtube-dl #for downloading video/audio from youtube
!pip install spleeter #for separating audio/song into parts (vocals, drums, bass, piano, other)
!pip3 install pydub

import spleeter
import youtube_dl
import pydub

from IPython.display import Audio, display
from IPython.display import HTML

import IPython.display as ipd
import sys

"""THIS CELL IS OPTIONAL; JUST IF YOU WANT TO DISPLAY"""

url = "dANdTnL7GxE" #the letter code after the "=" in the url
embed_url = "the entire url".format(url)
HTML('the embeded code') #you can find this when you click "share" and choose the "embed" option (iframe)

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

ydl_args = {
    'format': 'bestaudio/best',
    'outtmpl': 'filename.mp3'
}

ydl = youtube_dl.YoutubeDL(ydl_args)
ydl.download(['entire url'])

"""THIS CELL IS OPTIONAL; FOR DISPLAYING PART OF THE AUDIO"""

display(Audio(audio[:, 0*rate:40*rate], rate=rate))

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

!spleeter separate -p spleeter:4stems -o output/ filename.mp3   #the options are 2stems, 4stems, or 5stems

#below is for converting the .wav files into .mp3 files

from pydub import AudioSegment
sound = AudioSegment.from_wav("output/filename/vocals.wav")
sound.export("output/filename/vocals.mp3", format="mp3")
sound = AudioSegment.from_wav("output/filename/drums.wav")
sound.export("output/filename/drums.mp3", format="mp3")
sound = AudioSegment.from_wav("output/filename/bass.wav")
sound.export("output/filename/bass.mp3", format="mp3")
sound = AudioSegment.from_wav("output/filename/other.wav")
sound.export("output/filename/other.mp3", format="mp3")
sound = AudioSegment.from_wav("output/filename/piano.wav")
sound.export("output/filename/piano.mp3", format="mp3")

ipd.Audio('output/filename/vocals.mp3')

ipd.Audio('output/filename/drums.mp3')

ipd.Audio('output/filename/bass.mp3')

ipd.Audio('output/filename/other.mp3')

ipd.Audio('output/filename/piano.mp3')
